package com.hiden.persistence.domain;

import java.util.Date;

public class CoopProfileDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.profile_id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Long profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.coop_id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Long coopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.date_created
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.last_updated
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.status
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.version
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coop_profile.type
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.id
     *
     * @return the value of coop_profile.id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.id
     *
     * @param id the value for coop_profile.id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.profile_id
     *
     * @return the value of coop_profile.profile_id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.profile_id
     *
     * @param profileId the value for coop_profile.profile_id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.coop_id
     *
     * @return the value of coop_profile.coop_id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Long getCoopId() {
        return coopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.coop_id
     *
     * @param coopId the value for coop_profile.coop_id
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setCoopId(Long coopId) {
        this.coopId = coopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.date_created
     *
     * @return the value of coop_profile.date_created
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.date_created
     *
     * @param dateCreated the value for coop_profile.date_created
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.last_updated
     *
     * @return the value of coop_profile.last_updated
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.last_updated
     *
     * @param lastUpdated the value for coop_profile.last_updated
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.status
     *
     * @return the value of coop_profile.status
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.status
     *
     * @param status the value for coop_profile.status
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.version
     *
     * @return the value of coop_profile.version
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.version
     *
     * @param version the value for coop_profile.version
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coop_profile.type
     *
     * @return the value of coop_profile.type
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coop_profile.type
     *
     * @param type the value for coop_profile.type
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }
}