package com.hiden.persistence.domain;

import java.util.Date;

public class PhoneBookListDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.id
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.version
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.date_created
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.last_updated
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.phone_num
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.is_read
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Byte isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.is_enabled
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Byte isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.is_success
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Byte isSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.user_id
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book_list.type
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.id
     *
     * @return the value of phone_book_list.id
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.id
     *
     * @param id the value for phone_book_list.id
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.version
     *
     * @return the value of phone_book_list.version
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.version
     *
     * @param version the value for phone_book_list.version
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.date_created
     *
     * @return the value of phone_book_list.date_created
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.date_created
     *
     * @param dateCreated the value for phone_book_list.date_created
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.last_updated
     *
     * @return the value of phone_book_list.last_updated
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.last_updated
     *
     * @param lastUpdated the value for phone_book_list.last_updated
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.phone_num
     *
     * @return the value of phone_book_list.phone_num
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.phone_num
     *
     * @param phoneNum the value for phone_book_list.phone_num
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.is_read
     *
     * @return the value of phone_book_list.is_read
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.is_read
     *
     * @param isRead the value for phone_book_list.is_read
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.is_enabled
     *
     * @return the value of phone_book_list.is_enabled
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Byte getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.is_enabled
     *
     * @param isEnabled the value for phone_book_list.is_enabled
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setIsEnabled(Byte isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.is_success
     *
     * @return the value of phone_book_list.is_success
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Byte getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.is_success
     *
     * @param isSuccess the value for phone_book_list.is_success
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setIsSuccess(Byte isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.user_id
     *
     * @return the value of phone_book_list.user_id
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.user_id
     *
     * @param userId the value for phone_book_list.user_id
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book_list.type
     *
     * @return the value of phone_book_list.type
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book_list.type
     *
     * @param type the value for phone_book_list.type
     *
     * @mbggenerated Tue Dec 06 17:36:24 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }
}