package com.hiden.persistence.domain;

import java.util.Date;

public class ProfileStatementDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.user_id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.date_created
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.last_updated
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.reply_content
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.version
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.device_id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.status
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile_statement.keyword
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.id
     *
     * @return the value of profile_statement.id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.id
     *
     * @param id the value for profile_statement.id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.user_id
     *
     * @return the value of profile_statement.user_id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.user_id
     *
     * @param userId the value for profile_statement.user_id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.date_created
     *
     * @return the value of profile_statement.date_created
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.date_created
     *
     * @param dateCreated the value for profile_statement.date_created
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.last_updated
     *
     * @return the value of profile_statement.last_updated
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.last_updated
     *
     * @param lastUpdated the value for profile_statement.last_updated
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.reply_content
     *
     * @return the value of profile_statement.reply_content
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.reply_content
     *
     * @param replyContent the value for profile_statement.reply_content
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.version
     *
     * @return the value of profile_statement.version
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.version
     *
     * @param version the value for profile_statement.version
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.device_id
     *
     * @return the value of profile_statement.device_id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.device_id
     *
     * @param deviceId the value for profile_statement.device_id
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.status
     *
     * @return the value of profile_statement.status
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.status
     *
     * @param status the value for profile_statement.status
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile_statement.keyword
     *
     * @return the value of profile_statement.keyword
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile_statement.keyword
     *
     * @param keyword the value for profile_statement.keyword
     *
     * @mbggenerated Fri Nov 25 09:40:03 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}