package com.hiden.persistence.domain;

import java.util.Date;

public class WxContactInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.user_id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.date_created
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.last_updated
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.wx_lemon_name
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private String wxLemonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.wx_opend_id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private String wxOpendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.wx_num
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private String wxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.wx_pic
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private String wxPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_contact_info.version
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.id
     *
     * @return the value of wx_contact_info.id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.id
     *
     * @param id the value for wx_contact_info.id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.user_id
     *
     * @return the value of wx_contact_info.user_id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.user_id
     *
     * @param userId the value for wx_contact_info.user_id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.date_created
     *
     * @return the value of wx_contact_info.date_created
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.date_created
     *
     * @param dateCreated the value for wx_contact_info.date_created
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.last_updated
     *
     * @return the value of wx_contact_info.last_updated
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.last_updated
     *
     * @param lastUpdated the value for wx_contact_info.last_updated
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.wx_lemon_name
     *
     * @return the value of wx_contact_info.wx_lemon_name
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public String getWxLemonName() {
        return wxLemonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.wx_lemon_name
     *
     * @param wxLemonName the value for wx_contact_info.wx_lemon_name
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setWxLemonName(String wxLemonName) {
        this.wxLemonName = wxLemonName == null ? null : wxLemonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.wx_opend_id
     *
     * @return the value of wx_contact_info.wx_opend_id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public String getWxOpendId() {
        return wxOpendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.wx_opend_id
     *
     * @param wxOpendId the value for wx_contact_info.wx_opend_id
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setWxOpendId(String wxOpendId) {
        this.wxOpendId = wxOpendId == null ? null : wxOpendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.wx_num
     *
     * @return the value of wx_contact_info.wx_num
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public String getWxNum() {
        return wxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.wx_num
     *
     * @param wxNum the value for wx_contact_info.wx_num
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setWxNum(String wxNum) {
        this.wxNum = wxNum == null ? null : wxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.wx_pic
     *
     * @return the value of wx_contact_info.wx_pic
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public String getWxPic() {
        return wxPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.wx_pic
     *
     * @param wxPic the value for wx_contact_info.wx_pic
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setWxPic(String wxPic) {
        this.wxPic = wxPic == null ? null : wxPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_contact_info.version
     *
     * @return the value of wx_contact_info.version
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_contact_info.version
     *
     * @param version the value for wx_contact_info.version
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}