package com.hiden.persistence.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxContactInfoDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public WxContactInfoDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setOffset(Integer offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public void setLimit(Integer limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNull() {
            addCriterion("date_created is null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNotNull() {
            addCriterion("date_created is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedEqualTo(Date value) {
            addCriterion("date_created =", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotEqualTo(Date value) {
            addCriterion("date_created <>", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThan(Date value) {
            addCriterion("date_created >", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_created >=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThan(Date value) {
            addCriterion("date_created <", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThanOrEqualTo(Date value) {
            addCriterion("date_created <=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIn(List<Date> values) {
            addCriterion("date_created in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotIn(List<Date> values) {
            addCriterion("date_created not in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedBetween(Date value1, Date value2) {
            addCriterion("date_created between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotBetween(Date value1, Date value2) {
            addCriterion("date_created not between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNull() {
            addCriterion("last_updated is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNotNull() {
            addCriterion("last_updated is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedEqualTo(Date value) {
            addCriterion("last_updated =", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotEqualTo(Date value) {
            addCriterion("last_updated <>", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThan(Date value) {
            addCriterion("last_updated >", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("last_updated >=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThan(Date value) {
            addCriterion("last_updated <", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("last_updated <=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIn(List<Date> values) {
            addCriterion("last_updated in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotIn(List<Date> values) {
            addCriterion("last_updated not in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedBetween(Date value1, Date value2) {
            addCriterion("last_updated between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("last_updated not between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameIsNull() {
            addCriterion("wx_lemon_name is null");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameIsNotNull() {
            addCriterion("wx_lemon_name is not null");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameEqualTo(String value) {
            addCriterion("wx_lemon_name =", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameNotEqualTo(String value) {
            addCriterion("wx_lemon_name <>", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameGreaterThan(String value) {
            addCriterion("wx_lemon_name >", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameGreaterThanOrEqualTo(String value) {
            addCriterion("wx_lemon_name >=", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameLessThan(String value) {
            addCriterion("wx_lemon_name <", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameLessThanOrEqualTo(String value) {
            addCriterion("wx_lemon_name <=", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameLike(String value) {
            addCriterion("wx_lemon_name like", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameNotLike(String value) {
            addCriterion("wx_lemon_name not like", value, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameIn(List<String> values) {
            addCriterion("wx_lemon_name in", values, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameNotIn(List<String> values) {
            addCriterion("wx_lemon_name not in", values, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameBetween(String value1, String value2) {
            addCriterion("wx_lemon_name between", value1, value2, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxLemonNameNotBetween(String value1, String value2) {
            addCriterion("wx_lemon_name not between", value1, value2, "wxLemonName");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdIsNull() {
            addCriterion("wx_opend_id is null");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdIsNotNull() {
            addCriterion("wx_opend_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdEqualTo(String value) {
            addCriterion("wx_opend_id =", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdNotEqualTo(String value) {
            addCriterion("wx_opend_id <>", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdGreaterThan(String value) {
            addCriterion("wx_opend_id >", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdGreaterThanOrEqualTo(String value) {
            addCriterion("wx_opend_id >=", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdLessThan(String value) {
            addCriterion("wx_opend_id <", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdLessThanOrEqualTo(String value) {
            addCriterion("wx_opend_id <=", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdLike(String value) {
            addCriterion("wx_opend_id like", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdNotLike(String value) {
            addCriterion("wx_opend_id not like", value, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdIn(List<String> values) {
            addCriterion("wx_opend_id in", values, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdNotIn(List<String> values) {
            addCriterion("wx_opend_id not in", values, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdBetween(String value1, String value2) {
            addCriterion("wx_opend_id between", value1, value2, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxOpendIdNotBetween(String value1, String value2) {
            addCriterion("wx_opend_id not between", value1, value2, "wxOpendId");
            return (Criteria) this;
        }

        public Criteria andWxNumIsNull() {
            addCriterion("wx_num is null");
            return (Criteria) this;
        }

        public Criteria andWxNumIsNotNull() {
            addCriterion("wx_num is not null");
            return (Criteria) this;
        }

        public Criteria andWxNumEqualTo(String value) {
            addCriterion("wx_num =", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumNotEqualTo(String value) {
            addCriterion("wx_num <>", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumGreaterThan(String value) {
            addCriterion("wx_num >", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumGreaterThanOrEqualTo(String value) {
            addCriterion("wx_num >=", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumLessThan(String value) {
            addCriterion("wx_num <", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumLessThanOrEqualTo(String value) {
            addCriterion("wx_num <=", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumLike(String value) {
            addCriterion("wx_num like", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumNotLike(String value) {
            addCriterion("wx_num not like", value, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumIn(List<String> values) {
            addCriterion("wx_num in", values, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumNotIn(List<String> values) {
            addCriterion("wx_num not in", values, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumBetween(String value1, String value2) {
            addCriterion("wx_num between", value1, value2, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxNumNotBetween(String value1, String value2) {
            addCriterion("wx_num not between", value1, value2, "wxNum");
            return (Criteria) this;
        }

        public Criteria andWxPicIsNull() {
            addCriterion("wx_pic is null");
            return (Criteria) this;
        }

        public Criteria andWxPicIsNotNull() {
            addCriterion("wx_pic is not null");
            return (Criteria) this;
        }

        public Criteria andWxPicEqualTo(String value) {
            addCriterion("wx_pic =", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicNotEqualTo(String value) {
            addCriterion("wx_pic <>", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicGreaterThan(String value) {
            addCriterion("wx_pic >", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicGreaterThanOrEqualTo(String value) {
            addCriterion("wx_pic >=", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicLessThan(String value) {
            addCriterion("wx_pic <", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicLessThanOrEqualTo(String value) {
            addCriterion("wx_pic <=", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicLike(String value) {
            addCriterion("wx_pic like", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicNotLike(String value) {
            addCriterion("wx_pic not like", value, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicIn(List<String> values) {
            addCriterion("wx_pic in", values, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicNotIn(List<String> values) {
            addCriterion("wx_pic not in", values, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicBetween(String value1, String value2) {
            addCriterion("wx_pic between", value1, value2, "wxPic");
            return (Criteria) this;
        }

        public Criteria andWxPicNotBetween(String value1, String value2) {
            addCriterion("wx_pic not between", value1, value2, "wxPic");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_contact_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 23 15:02:15 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}