package com.hiden.persistence.domain;

import java.util.Date;

public class WxDeviceTaskJobDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.id
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.user_id
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.date_created
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.last_updated
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.task_name
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.version
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.status
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.type
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.task_value
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private String taskValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.task_pic
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private String taskPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.start_time
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.comment
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.address
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.success_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Integer successNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.error_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Integer errorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.delete_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Integer deleteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.nodo_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Integer nodoNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_device_task_job.fail_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    private Integer failNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.id
     *
     * @return the value of wx_device_task_job.id
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.id
     *
     * @param id the value for wx_device_task_job.id
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.user_id
     *
     * @return the value of wx_device_task_job.user_id
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.user_id
     *
     * @param userId the value for wx_device_task_job.user_id
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.date_created
     *
     * @return the value of wx_device_task_job.date_created
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.date_created
     *
     * @param dateCreated the value for wx_device_task_job.date_created
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.last_updated
     *
     * @return the value of wx_device_task_job.last_updated
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.last_updated
     *
     * @param lastUpdated the value for wx_device_task_job.last_updated
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.task_name
     *
     * @return the value of wx_device_task_job.task_name
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.task_name
     *
     * @param taskName the value for wx_device_task_job.task_name
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.version
     *
     * @return the value of wx_device_task_job.version
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.version
     *
     * @param version the value for wx_device_task_job.version
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.status
     *
     * @return the value of wx_device_task_job.status
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.status
     *
     * @param status the value for wx_device_task_job.status
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.type
     *
     * @return the value of wx_device_task_job.type
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.type
     *
     * @param type the value for wx_device_task_job.type
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.task_value
     *
     * @return the value of wx_device_task_job.task_value
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public String getTaskValue() {
        return taskValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.task_value
     *
     * @param taskValue the value for wx_device_task_job.task_value
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setTaskValue(String taskValue) {
        this.taskValue = taskValue == null ? null : taskValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.task_pic
     *
     * @return the value of wx_device_task_job.task_pic
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public String getTaskPic() {
        return taskPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.task_pic
     *
     * @param taskPic the value for wx_device_task_job.task_pic
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setTaskPic(String taskPic) {
        this.taskPic = taskPic == null ? null : taskPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.start_time
     *
     * @return the value of wx_device_task_job.start_time
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.start_time
     *
     * @param startTime the value for wx_device_task_job.start_time
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.comment
     *
     * @return the value of wx_device_task_job.comment
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.comment
     *
     * @param comment the value for wx_device_task_job.comment
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.address
     *
     * @return the value of wx_device_task_job.address
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.address
     *
     * @param address the value for wx_device_task_job.address
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.success_num
     *
     * @return the value of wx_device_task_job.success_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Integer getSuccessNum() {
        return successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.success_num
     *
     * @param successNum the value for wx_device_task_job.success_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setSuccessNum(Integer successNum) {
        this.successNum = successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.error_num
     *
     * @return the value of wx_device_task_job.error_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Integer getErrorNum() {
        return errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.error_num
     *
     * @param errorNum the value for wx_device_task_job.error_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setErrorNum(Integer errorNum) {
        this.errorNum = errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.delete_num
     *
     * @return the value of wx_device_task_job.delete_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Integer getDeleteNum() {
        return deleteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.delete_num
     *
     * @param deleteNum the value for wx_device_task_job.delete_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setDeleteNum(Integer deleteNum) {
        this.deleteNum = deleteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.nodo_num
     *
     * @return the value of wx_device_task_job.nodo_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Integer getNodoNum() {
        return nodoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.nodo_num
     *
     * @param nodoNum the value for wx_device_task_job.nodo_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setNodoNum(Integer nodoNum) {
        this.nodoNum = nodoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_device_task_job.fail_num
     *
     * @return the value of wx_device_task_job.fail_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public Integer getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_device_task_job.fail_num
     *
     * @param failNum the value for wx_device_task_job.fail_num
     *
     * @mbggenerated Thu Dec 08 17:55:06 CST 2016
     */
    public void setFailNum(Integer failNum) {
        this.failNum = failNum;
    }
}