package com.hiden.persistence.domain;

import java.util.Date;

public class WxFriendList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.version
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.wechat_num
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private String wechatNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.wechat_remark
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private String wechatRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.wechat_nick
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private String wechatNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.wechat_phone
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private String wechatPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.wechat_mainuser
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private String wechatMainuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.date_created
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.last_updated
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.user_id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_friend_list.wx_id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    private Long wxId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.id
     *
     * @return the value of wx_friend_list.id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.id
     *
     * @param id the value for wx_friend_list.id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.version
     *
     * @return the value of wx_friend_list.version
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.version
     *
     * @param version the value for wx_friend_list.version
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.wechat_num
     *
     * @return the value of wx_friend_list.wechat_num
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public String getWechatNum() {
        return wechatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.wechat_num
     *
     * @param wechatNum the value for wx_friend_list.wechat_num
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setWechatNum(String wechatNum) {
        this.wechatNum = wechatNum == null ? null : wechatNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.wechat_remark
     *
     * @return the value of wx_friend_list.wechat_remark
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public String getWechatRemark() {
        return wechatRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.wechat_remark
     *
     * @param wechatRemark the value for wx_friend_list.wechat_remark
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setWechatRemark(String wechatRemark) {
        this.wechatRemark = wechatRemark == null ? null : wechatRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.wechat_nick
     *
     * @return the value of wx_friend_list.wechat_nick
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public String getWechatNick() {
        return wechatNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.wechat_nick
     *
     * @param wechatNick the value for wx_friend_list.wechat_nick
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setWechatNick(String wechatNick) {
        this.wechatNick = wechatNick == null ? null : wechatNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.wechat_phone
     *
     * @return the value of wx_friend_list.wechat_phone
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public String getWechatPhone() {
        return wechatPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.wechat_phone
     *
     * @param wechatPhone the value for wx_friend_list.wechat_phone
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setWechatPhone(String wechatPhone) {
        this.wechatPhone = wechatPhone == null ? null : wechatPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.wechat_mainuser
     *
     * @return the value of wx_friend_list.wechat_mainuser
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public String getWechatMainuser() {
        return wechatMainuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.wechat_mainuser
     *
     * @param wechatMainuser the value for wx_friend_list.wechat_mainuser
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setWechatMainuser(String wechatMainuser) {
        this.wechatMainuser = wechatMainuser == null ? null : wechatMainuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.date_created
     *
     * @return the value of wx_friend_list.date_created
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.date_created
     *
     * @param dateCreated the value for wx_friend_list.date_created
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.last_updated
     *
     * @return the value of wx_friend_list.last_updated
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.last_updated
     *
     * @param lastUpdated the value for wx_friend_list.last_updated
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.user_id
     *
     * @return the value of wx_friend_list.user_id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.user_id
     *
     * @param userId the value for wx_friend_list.user_id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_friend_list.wx_id
     *
     * @return the value of wx_friend_list.wx_id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Long getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_friend_list.wx_id
     *
     * @param wxId the value for wx_friend_list.wx_id
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setWxId(Long wxId) {
        this.wxId = wxId;
    }
}