package com.hiden.persistence.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxFriendListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public WxFriendListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setOffset(Integer offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public void setLimit(Integer limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andWechatNumIsNull() {
            addCriterion("wechat_num is null");
            return (Criteria) this;
        }

        public Criteria andWechatNumIsNotNull() {
            addCriterion("wechat_num is not null");
            return (Criteria) this;
        }

        public Criteria andWechatNumEqualTo(String value) {
            addCriterion("wechat_num =", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumNotEqualTo(String value) {
            addCriterion("wechat_num <>", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumGreaterThan(String value) {
            addCriterion("wechat_num >", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_num >=", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumLessThan(String value) {
            addCriterion("wechat_num <", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumLessThanOrEqualTo(String value) {
            addCriterion("wechat_num <=", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumLike(String value) {
            addCriterion("wechat_num like", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumNotLike(String value) {
            addCriterion("wechat_num not like", value, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumIn(List<String> values) {
            addCriterion("wechat_num in", values, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumNotIn(List<String> values) {
            addCriterion("wechat_num not in", values, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumBetween(String value1, String value2) {
            addCriterion("wechat_num between", value1, value2, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatNumNotBetween(String value1, String value2) {
            addCriterion("wechat_num not between", value1, value2, "wechatNum");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkIsNull() {
            addCriterion("wechat_remark is null");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkIsNotNull() {
            addCriterion("wechat_remark is not null");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkEqualTo(String value) {
            addCriterion("wechat_remark =", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkNotEqualTo(String value) {
            addCriterion("wechat_remark <>", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkGreaterThan(String value) {
            addCriterion("wechat_remark >", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_remark >=", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkLessThan(String value) {
            addCriterion("wechat_remark <", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkLessThanOrEqualTo(String value) {
            addCriterion("wechat_remark <=", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkLike(String value) {
            addCriterion("wechat_remark like", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkNotLike(String value) {
            addCriterion("wechat_remark not like", value, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkIn(List<String> values) {
            addCriterion("wechat_remark in", values, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkNotIn(List<String> values) {
            addCriterion("wechat_remark not in", values, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkBetween(String value1, String value2) {
            addCriterion("wechat_remark between", value1, value2, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatRemarkNotBetween(String value1, String value2) {
            addCriterion("wechat_remark not between", value1, value2, "wechatRemark");
            return (Criteria) this;
        }

        public Criteria andWechatNickIsNull() {
            addCriterion("wechat_nick is null");
            return (Criteria) this;
        }

        public Criteria andWechatNickIsNotNull() {
            addCriterion("wechat_nick is not null");
            return (Criteria) this;
        }

        public Criteria andWechatNickEqualTo(String value) {
            addCriterion("wechat_nick =", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickNotEqualTo(String value) {
            addCriterion("wechat_nick <>", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickGreaterThan(String value) {
            addCriterion("wechat_nick >", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_nick >=", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickLessThan(String value) {
            addCriterion("wechat_nick <", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickLessThanOrEqualTo(String value) {
            addCriterion("wechat_nick <=", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickLike(String value) {
            addCriterion("wechat_nick like", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickNotLike(String value) {
            addCriterion("wechat_nick not like", value, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickIn(List<String> values) {
            addCriterion("wechat_nick in", values, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickNotIn(List<String> values) {
            addCriterion("wechat_nick not in", values, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickBetween(String value1, String value2) {
            addCriterion("wechat_nick between", value1, value2, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatNickNotBetween(String value1, String value2) {
            addCriterion("wechat_nick not between", value1, value2, "wechatNick");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneIsNull() {
            addCriterion("wechat_phone is null");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneIsNotNull() {
            addCriterion("wechat_phone is not null");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneEqualTo(String value) {
            addCriterion("wechat_phone =", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneNotEqualTo(String value) {
            addCriterion("wechat_phone <>", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneGreaterThan(String value) {
            addCriterion("wechat_phone >", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_phone >=", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneLessThan(String value) {
            addCriterion("wechat_phone <", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneLessThanOrEqualTo(String value) {
            addCriterion("wechat_phone <=", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneLike(String value) {
            addCriterion("wechat_phone like", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneNotLike(String value) {
            addCriterion("wechat_phone not like", value, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneIn(List<String> values) {
            addCriterion("wechat_phone in", values, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneNotIn(List<String> values) {
            addCriterion("wechat_phone not in", values, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneBetween(String value1, String value2) {
            addCriterion("wechat_phone between", value1, value2, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatPhoneNotBetween(String value1, String value2) {
            addCriterion("wechat_phone not between", value1, value2, "wechatPhone");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserIsNull() {
            addCriterion("wechat_mainuser is null");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserIsNotNull() {
            addCriterion("wechat_mainuser is not null");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserEqualTo(String value) {
            addCriterion("wechat_mainuser =", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserNotEqualTo(String value) {
            addCriterion("wechat_mainuser <>", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserGreaterThan(String value) {
            addCriterion("wechat_mainuser >", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_mainuser >=", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserLessThan(String value) {
            addCriterion("wechat_mainuser <", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserLessThanOrEqualTo(String value) {
            addCriterion("wechat_mainuser <=", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserLike(String value) {
            addCriterion("wechat_mainuser like", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserNotLike(String value) {
            addCriterion("wechat_mainuser not like", value, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserIn(List<String> values) {
            addCriterion("wechat_mainuser in", values, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserNotIn(List<String> values) {
            addCriterion("wechat_mainuser not in", values, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserBetween(String value1, String value2) {
            addCriterion("wechat_mainuser between", value1, value2, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andWechatMainuserNotBetween(String value1, String value2) {
            addCriterion("wechat_mainuser not between", value1, value2, "wechatMainuser");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNull() {
            addCriterion("date_created is null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNotNull() {
            addCriterion("date_created is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedEqualTo(Date value) {
            addCriterion("date_created =", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotEqualTo(Date value) {
            addCriterion("date_created <>", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThan(Date value) {
            addCriterion("date_created >", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_created >=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThan(Date value) {
            addCriterion("date_created <", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThanOrEqualTo(Date value) {
            addCriterion("date_created <=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIn(List<Date> values) {
            addCriterion("date_created in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotIn(List<Date> values) {
            addCriterion("date_created not in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedBetween(Date value1, Date value2) {
            addCriterion("date_created between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotBetween(Date value1, Date value2) {
            addCriterion("date_created not between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNull() {
            addCriterion("last_updated is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNotNull() {
            addCriterion("last_updated is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedEqualTo(Date value) {
            addCriterion("last_updated =", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotEqualTo(Date value) {
            addCriterion("last_updated <>", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThan(Date value) {
            addCriterion("last_updated >", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("last_updated >=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThan(Date value) {
            addCriterion("last_updated <", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("last_updated <=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIn(List<Date> values) {
            addCriterion("last_updated in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotIn(List<Date> values) {
            addCriterion("last_updated not in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedBetween(Date value1, Date value2) {
            addCriterion("last_updated between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("last_updated not between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andWxIdIsNull() {
            addCriterion("wx_id is null");
            return (Criteria) this;
        }

        public Criteria andWxIdIsNotNull() {
            addCriterion("wx_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxIdEqualTo(Long value) {
            addCriterion("wx_id =", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotEqualTo(Long value) {
            addCriterion("wx_id <>", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdGreaterThan(Long value) {
            addCriterion("wx_id >", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdGreaterThanOrEqualTo(Long value) {
            addCriterion("wx_id >=", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLessThan(Long value) {
            addCriterion("wx_id <", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdLessThanOrEqualTo(Long value) {
            addCriterion("wx_id <=", value, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdIn(List<Long> values) {
            addCriterion("wx_id in", values, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotIn(List<Long> values) {
            addCriterion("wx_id not in", values, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdBetween(Long value1, Long value2) {
            addCriterion("wx_id between", value1, value2, "wxId");
            return (Criteria) this;
        }

        public Criteria andWxIdNotBetween(Long value1, Long value2) {
            addCriterion("wx_id not between", value1, value2, "wxId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_friend_list
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 28 10:38:22 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_friend_list
     *
     * @mbggenerated Mon Nov 28 10:38:22 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}