package com.hiden.persistence.domain;

import java.util.Date;

public class WxPhoneResultDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.version
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.date_created
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.last_updated
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.phone_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private Long phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.wx_name
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private String wxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.device_info
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private String deviceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.from_wx_name
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private String fromWxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.from_wx_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private Long fromWxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_phone_result.user_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.id
     *
     * @return the value of wx_phone_result.id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.id
     *
     * @param id the value for wx_phone_result.id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.version
     *
     * @return the value of wx_phone_result.version
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.version
     *
     * @param version the value for wx_phone_result.version
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.date_created
     *
     * @return the value of wx_phone_result.date_created
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.date_created
     *
     * @param dateCreated the value for wx_phone_result.date_created
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.last_updated
     *
     * @return the value of wx_phone_result.last_updated
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.last_updated
     *
     * @param lastUpdated the value for wx_phone_result.last_updated
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.phone_id
     *
     * @return the value of wx_phone_result.phone_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public Long getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.phone_id
     *
     * @param phoneId the value for wx_phone_result.phone_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setPhoneId(Long phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.wx_name
     *
     * @return the value of wx_phone_result.wx_name
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.wx_name
     *
     * @param wxName the value for wx_phone_result.wx_name
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setWxName(String wxName) {
        this.wxName = wxName == null ? null : wxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.device_info
     *
     * @return the value of wx_phone_result.device_info
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.device_info
     *
     * @param deviceInfo the value for wx_phone_result.device_info
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setDeviceInfo(String deviceInfo) {
        this.deviceInfo = deviceInfo == null ? null : deviceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.from_wx_name
     *
     * @return the value of wx_phone_result.from_wx_name
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public String getFromWxName() {
        return fromWxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.from_wx_name
     *
     * @param fromWxName the value for wx_phone_result.from_wx_name
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setFromWxName(String fromWxName) {
        this.fromWxName = fromWxName == null ? null : fromWxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.from_wx_id
     *
     * @return the value of wx_phone_result.from_wx_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public Long getFromWxId() {
        return fromWxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.from_wx_id
     *
     * @param fromWxId the value for wx_phone_result.from_wx_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setFromWxId(Long fromWxId) {
        this.fromWxId = fromWxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_phone_result.user_id
     *
     * @return the value of wx_phone_result.user_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_phone_result.user_id
     *
     * @param userId the value for wx_phone_result.user_id
     *
     * @mbggenerated Wed Dec 07 10:37:50 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}