package com.hiden.persistence;

import com.hiden.persistence.domain.DeviceInfoDO;
import com.hiden.persistence.domain.DeviceInfoDOExample;
import com.hiden.web.model.WxInfoVo;
import com.hiden.web.model.WxNumVo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface DeviceInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int countByExample(DeviceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int deleteByExample(DeviceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int insert(DeviceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int insertSelective(DeviceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    List<DeviceInfoDO> selectByExample(DeviceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    DeviceInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") DeviceInfoDO record, @Param("example") DeviceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int updateByExample(@Param("record") DeviceInfoDO record, @Param("example") DeviceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int updateByPrimaryKeySelective(DeviceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Mon Nov 21 14:10:35 CST 2016
     */
    int updateByPrimaryKey(DeviceInfoDO record);
    
    //根据对应的userId来查找对应的微信基本全内容值
    List<WxInfoVo> selectDeviceByUserId(Map map);
    //根据对应的userId来查找对应数目
    int selectTotalCount(Long userId);
    
    //根据用户的id来查找deviceIds的结合内容-
    String selectDeviceIdsByUserId(Long userId);
    
    
    //根据id来查找对应的用户对应的微信号的集合内容
    List<WxNumVo> selectWxNumByUserId(Long userId);
}