package com.hiden.persistence;

import com.hiden.persistence.domain.JobCacheDo;
import com.hiden.persistence.domain.JobCacheDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
@Repository
public interface JobCacheDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int countByExample(JobCacheDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int deleteByExample(JobCacheDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int insert(JobCacheDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int insertSelective(JobCacheDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    List<JobCacheDo> selectByExampleWithRowbounds(JobCacheDoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    List<JobCacheDo> selectByExample(JobCacheDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    JobCacheDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") JobCacheDo record, @Param("example") JobCacheDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int updateByExample(@Param("record") JobCacheDo record, @Param("example") JobCacheDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int updateByPrimaryKeySelective(JobCacheDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_cache
     *
     * @mbggenerated Thu Dec 01 17:46:46 CST 2016
     */
    int updateByPrimaryKey(JobCacheDo record);
}