package com.hiden.persistence;

import com.hiden.persistence.domain.MessageSummaryDO;
import com.hiden.persistence.domain.MessageSummaryDOExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MessageSummaryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int countByExample(MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int deleteByExample(MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int insert(MessageSummaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int insertSelective(MessageSummaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    List<MessageSummaryDO> selectByExample(MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    MessageSummaryDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageSummaryDO record, @Param("example") MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByExample(@Param("record") MessageSummaryDO record, @Param("example") MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(MessageSummaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByPrimaryKey(MessageSummaryDO record);
}