package com.hiden.persistence;

import com.hiden.persistence.domain.PhoneBookListDo;
import com.hiden.persistence.domain.PhoneBookListDoExample;
import com.hiden.web.model.PhoneInfoVo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
@Repository
public interface PhoneBookListDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int countByExample(PhoneBookListDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int deleteByExample(PhoneBookListDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int insert(PhoneBookListDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int insertSelective(PhoneBookListDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    List<PhoneBookListDo> selectByExampleWithRowbounds(PhoneBookListDoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    List<PhoneBookListDo> selectByExample(PhoneBookListDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    PhoneBookListDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") PhoneBookListDo record, @Param("example") PhoneBookListDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int updateByExample(@Param("record") PhoneBookListDo record, @Param("example") PhoneBookListDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int updateByPrimaryKeySelective(PhoneBookListDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book_list
     *
     * @mbggenerated Tue Dec 06 12:07:42 CST 2016
     */
    int updateByPrimaryKey(PhoneBookListDo record);
    
    
    //根据对应的userId来查找对应数目
    int selectTotalCount(Long userId);
    
    //来查找对应终端有效的电话本有效个数
    List<PhoneInfoVo> selectPhoneListDataByUserId(Map map);
}