package com.hiden.persistence;

import com.hiden.persistence.domain.ProfileDO;
import com.hiden.persistence.domain.ProfileDOExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProfileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int countByExample(ProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int deleteByExample(ProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int insert(ProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int insertSelective(ProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    List<ProfileDO> selectByExample(ProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    ProfileDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProfileDO record, @Param("example") ProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByExample(@Param("record") ProfileDO record, @Param("example") ProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(ProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByPrimaryKey(ProfileDO record);
}