package com.hiden.persistence;

import com.hiden.persistence.domain.TaskAndDeviceDo;
import com.hiden.persistence.domain.TaskAndDeviceDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface TaskAndDeviceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int countByExample(TaskAndDeviceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int deleteByExample(TaskAndDeviceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int insert(TaskAndDeviceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int insertSelective(TaskAndDeviceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    List<TaskAndDeviceDo> selectByExample(TaskAndDeviceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    TaskAndDeviceDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaskAndDeviceDo record, @Param("example") TaskAndDeviceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByExample(@Param("record") TaskAndDeviceDo record, @Param("example") TaskAndDeviceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByPrimaryKeySelective(TaskAndDeviceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_and_device
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByPrimaryKey(TaskAndDeviceDo record);
    
    
    
    //根据对应的设备来查出对应的未执行的任务的总数
    int selectTotalSizeByDeviceId(Long id);
}