package com.hiden.persistence;

import com.hiden.persistence.domain.WechatProfileDO;
import com.hiden.persistence.domain.WechatProfileDOExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface WechatProfileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int countByExample(WechatProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int deleteByExample(WechatProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int insert(WechatProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int insertSelective(WechatProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    List<WechatProfileDO> selectByExample(WechatProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    WechatProfileDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") WechatProfileDO record, @Param("example") WechatProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByExample(@Param("record") WechatProfileDO record, @Param("example") WechatProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(WechatProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_profile
     *
     * @mbggenerated Tue Nov 01 12:19:53 CST 2016
     */
    int updateByPrimaryKey(WechatProfileDO record);
}