package com.hiden.persistence;

import com.hiden.persistence.domain.WxContactInfoDO;
import com.hiden.persistence.domain.WxContactInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
@Repository
public interface WxContactInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int countByExample(WxContactInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int deleteByExample(WxContactInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int insert(WxContactInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int insertSelective(WxContactInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    List<WxContactInfoDO> selectByExampleWithRowbounds(WxContactInfoDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    List<WxContactInfoDO> selectByExample(WxContactInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    WxContactInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") WxContactInfoDO record, @Param("example") WxContactInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int updateByExample(@Param("record") WxContactInfoDO record, @Param("example") WxContactInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int updateByPrimaryKeySelective(WxContactInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_contact_info
     *
     * @mbggenerated Wed Nov 23 15:02:15 CST 2016
     */
    int updateByPrimaryKey(WxContactInfoDO record);
    
    
    //根据对应的userId来查找对应数目
    int selectTotalCount(Long userId);
}