package com.hiden.persistence;

import com.hiden.persistence.domain.WxDeviceTaskJobDo;
import com.hiden.persistence.domain.WxDeviceTaskJobDoExample;
import com.hiden.web.model.PcTaskRecordVo;
import com.hiden.web.model.TaskRecordVo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface WxDeviceTaskJobDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int countByExample(WxDeviceTaskJobDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int deleteByExample(WxDeviceTaskJobDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int insert(WxDeviceTaskJobDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int insertSelective(WxDeviceTaskJobDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    List<WxDeviceTaskJobDo> selectByExample(WxDeviceTaskJobDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    WxDeviceTaskJobDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") WxDeviceTaskJobDo record, @Param("example") WxDeviceTaskJobDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByExample(@Param("record") WxDeviceTaskJobDo record, @Param("example") WxDeviceTaskJobDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByPrimaryKeySelective(WxDeviceTaskJobDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_device_task_job
     *
     * @mbggenerated Mon Nov 21 12:34:48 CST 2016
     */
    int updateByPrimaryKey(WxDeviceTaskJobDo record);
    
    
    //根据对应的设备的info来查找对应的job的数据
    List<WxDeviceTaskJobDo> selectTaskByDeviceInfo(Map map);
    //优化版内容
    List<TaskRecordVo> selectTaskInfoByDeviceInf(Map map);
  
    
    
    
    //根据用户列表来获取对应的列表信息内容
    List<TaskRecordVo> selectTaskListRecordByDeviceInfo(Map map);
    
    //根据用户id来查找对应的用户任务列表信息内容
    //selectPcTaskRecordInfoByUserIdInf
    List<PcTaskRecordVo> selectPcTaskRecordInfoByUserIdInf(Map map);
    //优化版本内容：selectPcTaskRecordInfoByUserIdInfPlusPlus
    List<PcTaskRecordVo> selectPcTaskRecordInfoByUserIdInfPlusPlus(Map map);
    
    
    
    //根据不一样的状态来查找对应的总数内容
    int selectTotalSizeByStatus(Map map);
    
    
    //设置utf8mb4保存设置编码
    int setUtf8mb4Charat();
    
    
    //以任务内容为依据的排序内容
    //进行任务的排列信息内容来查找对应的全部任务内容值
    List<WxDeviceTaskJobDo> selectPcFinalJobList(Map map);
    //根据job的id的集合内容来查找对应的详情内容值
    List<PcTaskRecordVo> selectPcFinalJobDetailList(Map map);
    //查找对应的任务个数
    int selectPcFinalJobListSize(Map map);
    
    
    //更新最实时的任务数目量
    int updateJobNums(Long id);
}