package com.hiden.persistence;

import com.hiden.persistence.domain.WxFriendList;
import com.hiden.persistence.domain.WxFriendListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
@Repository
public interface WxFriendListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int countByExample(WxFriendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int deleteByExample(WxFriendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int insert(WxFriendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int insertSelective(WxFriendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    List<WxFriendList> selectByExampleWithRowbounds(WxFriendListExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    List<WxFriendList> selectByExample(WxFriendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    WxFriendList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") WxFriendList record, @Param("example") WxFriendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int updateByExample(@Param("record") WxFriendList record, @Param("example") WxFriendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int updateByPrimaryKeySelective(WxFriendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_friend_list
     *
     * @mbggenerated Wed Nov 23 12:13:03 CST 2016
     */
    int updateByPrimaryKey(WxFriendList record);
    
    
    //根据对应的userId来查找对应数目
    int selectTotalCount(Long userId);
    
}