/**
 * Created by xiuxiu on 2016/12/8.
 */

var emoji = function(){
    var emojiData = [
        {
            classN:'emoji2600',
            wechat:'☀'
        },
        {
            classN:'emoji2601',
            wechat:'☁'
        },
        {
            classN:'emoji2614',
            wechat:'☔'
        },
        {
            classN:'emoji26c4',
            wechat:'⛄'
        },
        {
            classN:'emoji26a1',
            wechat:'⚡'
        },
        {
            classN:'emoji1f300',
            wechat:'🌀'
        },
        {
            classN:'emoji1f301',
            wechat:'🌁'
        },
        {
            classN:'emoji1f302',
            wechat:'🌂'
        },
        {
            classN:'emoji1f303',
            wechat:'🌃'
        },
        {
            classN:'emoji1f304',
            wechat:'🌄'
        },
        {
            classN:'emoji1f305',
            wechat:'🌅'
        },
        {
            classN:'emoji1f306',
            wechat:'🌆'
        },
        {
            classN:'emoji1f307',
            wechat:'🌇'
        },
        {
            classN:'emoji1f308',
            wechat:'🌈'
        },
        {
            classN:'emoji2744',
            wechat:'❄'
        },
        {
            classN:'emoji26c5',
            wechat:'⛅'
        },
        {
            classN:'emoji1f309',
            wechat:'🌉'
        },
        {
            classN:'emoji1f30a',
            wechat:'🌊'
        },
        {
            classN:'emoji1f30b',
            wechat:'🌋'
        },
        {
            classN:'emoji1f30c',
            wechat:'🌌'
        },
        {
            classN:'emoji1f30f',
            wechat:'🌏'
        },
        {
            classN:'emoji1f311',
            wechat:'🌑'
        },
        {
            classN:'emoji1f314',
            wechat:'🌔'
        },
        {
            classN:'emoji1f313',
            wechat:'🌓'
        },
        {
            classN:'emoji1f319',
            wechat:'🌙'
        },
        {
            classN:'emoji1f315',
            wechat:'🌕'
        },
        {
            classN:'emoji1f31b',
            wechat:'🌛'
        },
        {
            classN:'emoji1f31f',
            wechat:'🌟'
        },
        {
            classN:'emoji1f320',
            wechat:'🌠'
        },
        {
            classN:'emoji1f550',
            wechat:'🕐'
        },
        {
            classN:'emoji1f551',
            wechat:'🕑'
        },
        {
            classN:'emoji1f552',
            wechat:'🕒'
        },
        {
            classN:'emoji1f553',
            wechat:'🕓'
        },
        {
            classN:'emoji1f554',
            wechat:'🕔'
        },
        {
            classN:'emoji1f555',
            wechat:'🕕'
        },
        {
            classN:'emoji1f556',
            wechat:'🕖'
        },
        {
            classN:'emoji1f557',
            wechat:'🕗'
        },
        {
            classN:'emoji1f558',
            wechat:'🕘'
        },
        {
            classN:'emoji1f559',
            wechat:'🕙'
        },
        {
            classN:'emoji1f55a',
            wechat:'🕚'
        },
        {
            classN:'emoji1f55b',
            wechat:'🕛'
        },
        {
            classN:'emoji231a',
            wechat:'⌚'
        },
        {
            classN:'emoji231b',
            wechat:'⌛'
        },
        {
            classN:'emoji23f0',
            wechat:'⏰'
        },
        {
            classN:'emoji23f3',
            wechat:'⏳'
        },
        {
            classN:'emoji2648',
            wechat:'♈'
        },
        {
            classN:'emoji2649',
            wechat:'♉'
        },
        {
            classN:'emoji264a',
            wechat:'♊'
        },
        {
            classN:'emoji264b',
            wechat:'♋'
        },
        {
            classN:'emoji264c',
            wechat:'♌'
        },
        {
            classN:'emoji264d',
            wechat:'♍'
        },
        {
            classN:'emoji264e',
            wechat:'♎'
        },
        {
            classN:'emoji264f',
            wechat:'♏'
        },
        {
            classN:'emoji2650',
            wechat:'♐'
        },
        {
            classN:'emoji2651',
            wechat:'♑'
        },
        {
            classN:'emoji2652',
            wechat:'♒'
        },
        {
            classN:'emoji2653',
            wechat:'♓'
        },
        {
            classN:'emoji26ce',
            wechat:'⛎'
        },
        {
            classN:'emoji1f340',
            wechat:'🍀'
        },
        {
            classN:'emoji1f337',
            wechat:'🌷'
        },
        {
            classN:'emoji1f331',
            wechat:'🌱'
        },
        {
            classN:'emoji1f341',
            wechat:'🍁'
        },
        {
            classN:'emoji1f338',
            wechat:'🌸'
        },
        {
            classN:'emoji1f339',
            wechat:'🌹'
        },
        {
            classN:'emoji1f342',
            wechat:'🍂'
        },
        {
            classN:'emoji1f343',
            wechat:'🍃'
        },
        {
            classN:'emoji1f33a',
            wechat:'🌺'
        },
        {
            classN:'emoji1f33b',
            wechat:'🌻'
        },
        {
            classN:'emoji1f334',
            wechat:'🌴'
        },
        {
            classN:'emoji1f335',
            wechat:'🌵'
        },
        {
            classN:'emoji1f33e',
            wechat:'🌾'
        },
        {
            classN:'emoji1f33d',
            wechat:'🌽'
        },
        {
            classN:'emoji1f344',
            wechat:'🍄'
        },
        {
            classN:'emoji1f330',
            wechat:'🌰'
        },
        {
            classN:'emoji1f33c',
            wechat:'🌼'
        },
        {
            classN:'emoji1f33f',
            wechat:'🌿'
        },
        {
            classN:'emoji1f352',
            wechat:'🍒'
        },
        {
            classN:'emoji1f34c',
            wechat:'🍌'
        },
        {
            classN:'emoji1f34e',
            wechat:'🍎'
        },
        {
            classN:'emoji1f34a',
            wechat:'🍊'
        },
        {
            classN:'emoji1f353',
            wechat:'🍓'
        },
        {
            classN:'emoji1f349',
            wechat:'🍉'
        },
        {
            classN:'emoji1f345',
            wechat:'🍅'
        },
        {
            classN:'emoji1f346',
            wechat:'🍆'
        },
        {
            classN:'emoji1f348',
            wechat:'🍈'
        },
        {
            classN:'emoji1f34d',
            wechat:'🍍'
        },
        {
            classN:'emoji1f347',
            wechat:'🍇'
        },
        {
            classN:'emoji1f351',
            wechat:'🍑'
        },
        {
            classN:'emoji1f34f',
            wechat:'🍏'
        },
        {
            classN:'emoji1f440',
            wechat:'👀'
        },
        {
            classN:'emoji1f442',
            wechat:'👂'
        },
        {
            classN:'emoji1f443',
            wechat:'👃'
        },
        {
            classN:'emoji1f444',
            wechat:'👄'
        },
        {
            classN:'emoji1f445',
            wechat:'👅'
        },
        {
            classN:'emoji1f484',
            wechat:'💄'
        },
        {
            classN:'emoji1f485',
            wechat:'💅'
        },
        {
            classN:'emoji1f486',
            wechat:'💆'
        },
        {
            classN:'emoji1f487',
            wechat:'💇'
        },
        {
            classN:'emoji1f488',
            wechat:'💈'
        },
        {
            classN:'emoji1f464',
            wechat:'👤'
        },
        {
            classN:'emoji1f466',
            wechat:'👦'
        },
        {
            classN:'emoji1f467',
            wechat:'👧'
        },
        {
            classN:'emoji1f468',
            wechat:'👨'
        },
        {
            classN:'emoji1f469',
            wechat:'👩'
        },
        {
            classN:'emoji1f46a',
            wechat:'👪'
        },
        {
            classN:'emoji1f46b',
            wechat:'👫'
        },
        {
            classN:'emoji1f46e',
            wechat:'👮'
        },
        {
            classN:'emoji1f46f',
            wechat:'👯'
        },
        {
            classN:'emoji1f470',
            wechat:'👰'
        },
        {
            classN:'emoji1f471',
            wechat:'👱'
        },
        {
            classN:'emoji1f472',
            wechat:'👲'
        },
        {
            classN:'emoji1f473',
            wechat:'👳'
        },
        {
            classN:'emoji1f474',
            wechat:'👴'
        },
        {
            classN:'emoji1f475',
            wechat:'👵'
        },
        {
            classN:'emoji1f476',
            wechat:'👶'
        },
        {
            classN:'emoji1f477',
            wechat:'👷'
        },
        {
            classN:'emoji1f478',
            wechat:'👸'
        },
        {
            classN:'emoji1f479',
            wechat:'👹'
        },
        {
            classN:'emoji1f47a',
            wechat:'👺'
        },
        {
            classN:'emoji1f47b',
            wechat:'👻'
        },
        {
            classN:'emoji1f47c',
            wechat:'👼'
        },
        {
            classN:'emoji1f47d',
            wechat:'👽'
        },
        {
            classN:'emoji1f47e',
            wechat:'👾'
        },
        {
            classN:'emoji1f47f',
            wechat:'👿'
        },
        {
            classN:'emoji1f480',
            wechat:'💀'
        },
        {
            classN:'emoji1f481',
            wechat:'💁'
        },
        {
            classN:'emoji1f482',
            wechat:'💂'
        },
        {
            classN:'emoji1f483',
            wechat:'💃'
        },
        {
            classN:'emoji1f40c',
            wechat:'🐌'
        },
        {
            classN:'emoji1f40d',
            wechat:'🐍'
        },
        {
            classN:'emoji1f40e',
            wechat:'🐎'
        },
        {
            classN:'emoji1f414',
            wechat:'🐔'
        },
        {
            classN:'emoji1f417',
            wechat:'🐗'
        },
        {
            classN:'emoji1f42b',
            wechat:'🐫'
        },
        {
            classN:'emoji1f418',
            wechat:'🐘'
        },
        {
            classN:'emoji1f428',
            wechat:'🐨'
        },
        {
            classN:'emoji1f412',
            wechat:'🐒'
        },
        {
            classN:'emoji1f411',
            wechat:'🐑'
        },
        {
            classN:'emoji1f419',
            wechat:'🐙'
        },
        {
            classN:'emoji1f41a',
            wechat:'🐚'
        },
        {
            classN:'emoji1f41b',
            wechat:'🐛'
        },
        {
            classN:'emoji1f41c',
            wechat:'🐜'
        },
        {
            classN:'emoji1f41d',
            wechat:'🐝'
        },
        {
            classN:'emoji1f41e',
            wechat:'🐞'
        },
        {
            classN:'emoji1f420',
            wechat:'🐠'
        },
        {
            classN:'emoji1f421',
            wechat:'🐡'
        },
        {
            classN:'emoji1f422',
            wechat:'🐢'
        },
        {
            classN:'emoji1f424',
            wechat:'🐤'
        },
        {
            classN:'emoji1f425',
            wechat:'🐥'
        },
        {
            classN:'emoji1f426',
            wechat:'🐦'
        },
        {
            classN:'emoji1f423',
            wechat:'🐣'
        },
        {
            classN:'emoji1f427',
            wechat:'🐧'
        },
        {
            classN:'emoji1f429',
            wechat:'🐩'
        },
        {
            classN:'emoji1f41f',
            wechat:'🐟'
        },
        {
            classN:'emoji1f42c',
            wechat:'🐬'
        },
        {
            classN:'emoji1f42d',
            wechat:'🐭'
        },
        {
            classN:'emoji1f42f',
            wechat:'🐯'
        },
        {
            classN:'emoji1f431',
            wechat:'🐱'
        },
        {
            classN:'emoji1f433',
            wechat:'🐳'
        },
        {
            classN:'emoji1f434',
            wechat:'🐴'
        },
        {
            classN:'emoji1f435',
            wechat:'🐵'
        },
        {
            classN:'emoji1f436',
            wechat:'🐶'
        },
        {
            classN:'emoji1f437',
            wechat:'🐷'
        },
        {
            classN:'emoji1f43b',
            wechat:'🐻'
        },
        {
            classN:'emoji1f439',
            wechat:'🐹'
        },
        {
            classN:'emoji1f43a',
            wechat:'🐺'
        },
        {
            classN:'emoji1f42e',
            wechat:'🐮'
        },
        {
            classN:'emoji1f430',
            wechat:'🐰'
        },
        {
            classN:'emoji1f438',
            wechat:'🐸'
        },
        {
            classN:'emoji1f43e',
            wechat:'🐾'
        },
        {
            classN:'emoji1f432',
            wechat:'🐲'
        },
        {
            classN:'emoji1f43c',
            wechat:'🐼'
        },
        {
            classN:'emoji1f43d',
            wechat:'🐽'
        },
        {
            classN:'emoji1f620',
            wechat:'😠'
        },
        {
            classN:'emoji1f629',
            wechat:'😩'
        },
        {
            classN:'emoji1f632',
            wechat:'😲'
        },
        {
            classN:'emoji1f61e',
            wechat:'😞'
        },
        {
            classN:'emoji1f635',
            wechat:'😵'
        },
        {
            classN:'emoji1f630',
            wechat:'😰'
        },
        {
            classN:'emoji1f612',
            wechat:'😒'
        },
        {
            classN:'emoji1f60d',
            wechat:'😍'
        },
        {
            classN:'emoji1f624',
            wechat:'😤'
        },
        {
            classN:'emoji1f61c',
            wechat:'😜'
        },
        {
            classN:'emoji1f61d',
            wechat:'😝'
        },
        {
            classN:'emoji1f60b',
            wechat:'😋'
        },
        {
            classN:'emoji1f618',
            wechat:'😘'
        },
        {
            classN:'emoji1f61a',
            wechat:'😚'
        },
        {
            classN:'emoji1f637',
            wechat:'😷'
        },
        {
            classN:'emoji1f633',
            wechat:'😳'
        },
        {
            classN:'emoji1f603',
            wechat:'😃'
        },
        {
            classN:'emoji1f605',
            wechat:'😅'
        },
        {
            classN:'emoji1f606',
            wechat:'😆'
        },
        {
            classN:'emoji1f601',
            wechat:'😁'
        },
        {
            classN:'emoji1f602',
            wechat:'😂'
        },
        {
            classN:'emoji1f60a',
            wechat:'😊'
        },
        {
            classN:'emoji263a',
            wechat:'☺'
        },
        {
            classN:'emoji1f604',
            wechat:'😄'
        },
        {
            classN:'emoji1f622',
            wechat:'😢'
        },
        {
            classN:'emoji1f62d',
            wechat:'😭'
        },
        {
            classN:'emoji1f628',
            wechat:'😨'
        },
        {
            classN:'emoji1f623',
            wechat:'😣'
        },
        {
            classN:'emoji1f621',
            wechat:'😡'
        },
        {
            classN:'emoji1f60c',
            wechat:'😌'
        },
        {
            classN:'emoji1f616',
            wechat:'😖'
        },
        {
            classN:'emoji1f614',
            wechat:'😔'
        },
        {
            classN:'emoji1f631',
            wechat:'😱'
        },
        {
            classN:'emoji1f62a',
            wechat:'😪'
        },
        {
            classN:'emoji1f60f',
            wechat:'😏'
        },
        {
            classN:'emoji1f613',
            wechat:'😓'
        },
        {
            classN:'emoji1f625',
            wechat:'😥'
        },
        {
            classN:'emoji1f62b',
            wechat:'😫'
        },
        {
            classN:'emoji1f609',
            wechat:'😉'
        },
        {
            classN:'emoji1f63a',
            wechat:'😺'
        },
        {
            classN:'emoji1f638',
            wechat:'😸'
        },
        {
            classN:'emoji1f639',
            wechat:'😹'
        },
        {
            classN:'emoji1f63d',
            wechat:'😽'
        },
        {
            classN:'emoji1f63b',
            wechat:'😻'
        },
        {
            classN:'emoji1f63f',
            wechat:'😿'
        },
        {
            classN:'emoji1f63e',
            wechat:'😾'
        },
        {
            classN:'emoji1f63c',
            wechat:'😼'
        },
        {
            classN:'emoji1f640',
            wechat:'🙀'
        },
        {
            classN:'emoji1f645',
            wechat:'🙅'
        },
        {
            classN:'emoji1f646',
            wechat:'🙆'
        },
        {
            classN:'emoji1f647',
            wechat:'🙇'
        },
        {
            classN:'emoji1f648',
            wechat:'🙈'
        },
        {
            classN:'emoji1f64a',
            wechat:'🙊'
        },
        {
            classN:'emoji1f649',
            wechat:'🙉'
        },
        {
            classN:'emoji1f64b',
            wechat:'🙋'
        },
        {
            classN:'emoji1f64c',
            wechat:'🙌'
        },
        {
            classN:'emoji1f64d',
            wechat:'🙍'
        },
        {
            classN:'emoji1f64e',
            wechat:'🙎'
        },
        {
            classN:'emoji1f64f',
            wechat:'🙏'
        },
        {
            classN:'emoji1f3e0',
            wechat:'🏠'
        },
        {
            classN:'emoji1f3e1',
            wechat:'🏡'
        },
        {
            classN:'emoji1f3e2',
            wechat:'🏢'
        },
        {
            classN:'emoji1f3e3',
            wechat:'🏣'
        },
        {
            classN:'emoji1f3e5',
            wechat:'🏥'
        },
        {
            classN:'emoji1f3e6',
            wechat:'🏦'
        },
        {
            classN:'emoji1f3e7',
            wechat:'🏧'
        },
        {
            classN:'emoji1f3e8',
            wechat:'🏨'
        },
        {
            classN:'emoji1f3e9',
            wechat:'🏩'
        },
        {
            classN:'emoji1f3ea',
            wechat:'🏪'
        },
        {
            classN:'emoji1f3eb',
            wechat:'🏫'
        },
        {
            classN:'emoji26ea',
            wechat:'⛪'
        },
        {
            classN:'emoji26f2',
            wechat:'⛲'
        },
        {
            classN:'emoji1f3ec',
            wechat:'🏬'
        },
        {
            classN:'emoji1f3ef',
            wechat:'🏯'
        },
        {
            classN:'emoji1f3f0',
            wechat:'🏰'
        },
        {
            classN:'emoji1f3ed',
            wechat:'🏭'
        },
        {
            classN:'emoji2693',
            wechat:'⚓'
        },
        {
            classN:'emoji1f3ee',
            wechat:'🏮'
        },
        {
            classN:'emoji1f5fb',
            wechat:'🗻'
        },
        {
            classN:'emoji1f5fc',
            wechat:'🗼'
        },
        {
            classN:'emoji1f5fd',
            wechat:'🗽'
        },
        {
            classN:'emoji1f5fe',
            wechat:'🗾'
        },
        {
            classN:'emoji1f5ff',
            wechat:'🗿'
        },
        {
            classN:'emoji1f45e',
            wechat:'👞'
        },
        {
            classN:'emoji1f45f',
            wechat:'👟'
        },
        {
            classN:'emoji1f460',
            wechat:'👠'
        },
        {
            classN:'emoji1f461',
            wechat:'👡'
        },
        {
            classN:'emoji1f462',
            wechat:'👢'
        },
        {
            classN:'emoji1f463',
            wechat:'👣'
        },
        {
            classN:'emoji1f453',
            wechat:'👓'
        },
        {
            classN:'emoji1f455',
            wechat:'👕'
        },
        {
            classN:'emoji1f456',
            wechat:'👖'
        },
        {
            classN:'emoji1f451',
            wechat:'👑'
        },
        {
            classN:'emoji1f454',
            wechat:'👔'
        },
        {
            classN:'emoji1f452',
            wechat:'👒'
        },
        {
            classN:'emoji1f457',
            wechat:'👗'
        },
        {
            classN:'emoji1f458',
            wechat:'👘'
        },
        {
            classN:'emoji1f459',
            wechat:'👙'
        },
        {
            classN:'emoji1f45a',
            wechat:'👚'
        },
        {
            classN:'emoji1f45b',
            wechat:'👛'
        },
        {
            classN:'emoji1f45c',
            wechat:'👜'
        },
        {
            classN:'emoji1f45d',
            wechat:'👝'
        },
        {
            classN:'emoji1f4b0',
            wechat:'💰'
        },
        {
            classN:'emoji1f4b1',
            wechat:'💱'
        },
        {
            classN:'emoji1f4b9',
            wechat:'💹'
        },
        {
            classN:'emoji1f4b2',
            wechat:'💲'
        },
        {
            classN:'emoji1f4b3',
            wechat:'💳'
        },
        {
            classN:'emoji1f4b4',
            wechat:'💴'
        },
        {
            classN:'emoji1f4b5',
            wechat:'💵'
        },
        {
            classN:'emoji1f4b8',
            wechat:'💸'
        },
        {
            classN:'emoji1f525',
            wechat:'🔥'
        },
        {
            classN:'emoji1f526',
            wechat:'🔦'
        },
        {
            classN:'emoji1f527',
            wechat:'🔧'
        },
        {
            classN:'emoji1f528',
            wechat:'🔨'
        },
        {
            classN:'emoji1f529',
            wechat:'🔩'
        },
        {
            classN:'emoji1f52a',
            wechat:'🔪'
        },
        {
            classN:'emoji1f52b',
            wechat:'🔫'
        },
        {
            classN:'emoji1f52e',
            wechat:'🔮'
        },
        {
            classN:'emoji1f52f',
            wechat:'🔯'
        },
        {
            classN:'emoji1f530',
            wechat:'🔰'
        },
        {
            classN:'emoji1f531',
            wechat:'🔱'
        },
        {
            classN:'emoji1f489',
            wechat:'💉'
        },
        {
            classN:'emoji1f48a',
            wechat:'💊'
        },
        {
            classN:'emoji1f170',
            wechat:'🅰'
        },
        {
            classN:'emoji1f171',
            wechat:'🅱'
        },
        {
            classN:'emoji1f18e',
            wechat:'🆎'
        },
        {
            classN:'emoji1f17e',
            wechat:'🅾'
        },
        {
            classN:'emoji1f380',
            wechat:'🎀'
        },
        {
            classN:'emoji1f381',
            wechat:'🎁'
        },
        {
            classN:'emoji1f382',
            wechat:'🎂'
        },
        {
            classN:'emoji1f384',
            wechat:'🎄'
        },
        {
            classN:'emoji1f385',
            wechat:'🎅'
        },
        {
            classN:'emoji1f38c',
            wechat:'🎌'
        },
        {
            classN:'emoji1f386',
            wechat:'🎆'
        },
        {
            classN:'emoji1f388',
            wechat:'🎈'
        },
        {
            classN:'emoji1f389',
            wechat:'🎉'
        },
        {
            classN:'emoji1f38d',
            wechat:'🎍'
        },
        {
            classN:'emoji1f38e',
            wechat:'🎎'
        },
        {
            classN:'emoji1f393',
            wechat:'🎓'
        },
        {
            classN:'emoji1f392',
            wechat:'🎒'
        },
        {
            classN:'emoji1f38f',
            wechat:'🎏'
        },
        {
            classN:'emoji1f387',
            wechat:'🎇'
        },
        {
            classN:'emoji1f390',
            wechat:'🎐'
        },
        {
            classN:'emoji1f383',
            wechat:'🎃'
        },
        {
            classN:'emoji1f38a',
            wechat:'🎊'
        },
        {
            classN:'emoji1f38b',
            wechat:'🎋'
        },
        {
            classN:'emoji1f391',
            wechat:'🎑'
        },
        {
            classN:'emoji1f4df',
            wechat:'📟'
        },
        {
            classN:'emoji260e',
            wechat:'☎'
        },
        {
            classN:'emoji1f4de',
            wechat:'📞'
        },
        {
            classN:'emoji1f4f1',
            wechat:'📱'
        },
        {
            classN:'emoji1f4f2',
            wechat:'📲'
        },
        {
            classN:'emoji1f4dd',
            wechat:'📝'
        },
        {
            classN:'emoji1f4e0',
            wechat:'📠'
        },
        {
            classN:'emoji2709',
            wechat:'✉'
        },
        {
            classN:'emoji1f4e8',
            wechat:'📨'
        },
        {
            classN:'emoji1f4e9',
            wechat:'📩'
        },
        {
            classN:'emoji1f4ea',
            wechat:'📪'
        },
        {
            classN:'emoji1f4eb',
            wechat:'📫'
        },
        {
            classN:'emoji1f4ee',
            wechat:'📮'
        },
        {
            classN:'emoji1f4f0',
            wechat:'📰'
        },
        {
            classN:'emoji1f4e2',
            wechat:'📢'
        },
        {
            classN:'emoji1f4e3',
            wechat:'📣'
        },
        {
            classN:'emoji1f4e1',
            wechat:'📡'
        },
        {
            classN:'emoji1f4e4',
            wechat:'📤'
        },
        {
            classN:'emoji1f4e5',
            wechat:'📥'
        },
        {
            classN:'emoji1f4e6',
            wechat:'📦'
        },
        {
            classN:'emoji1f4e7',
            wechat:'📧'
        },
        {
            classN:'emoji1f520',
            wechat:'🔠'
        },
        {
            classN:'emoji1f521',
            wechat:'🔡'
        },
        {
            classN:'emoji1f522',
            wechat:'🔢'
        },
        {
            classN:'emoji1f523',
            wechat:'🔣'
        },
        {
            classN:'emoji1f524',
            wechat:'🔤'
        },
        {
            classN:'emoji2712',
            wechat:'✒'
        },
        {
            classN:'emoji1f4ba',
            wechat:'💺'
        },
        {
            classN:'emoji1f4bb',
            wechat:'💻'
        },
        {
            classN:'emoji270f',
            wechat:'✏'
        },
        {
            classN:'emoji1f4ce',
            wechat:'📎'
        },
        {
            classN:'emoji1f4bc',
            wechat:'💼'
        },
        {
            classN:'emoji1f4bd',
            wechat:'💽'
        },
        {
            classN:'emoji1f4be',
            wechat:'💾'
        },
        {
            classN:'emoji1f4bf',
            wechat:'💿'
        },
        {
            classN:'emoji1f4c0',
            wechat:'📀'
        },
        {
            classN:'emoji2702',
            wechat:'✂'
        },
        {
            classN:'emoji1f4cd',
            wechat:'📍'
        },
        {
            classN:'emoji1f4c3',
            wechat:'📃'
        },
        {
            classN:'emoji1f4c4',
            wechat:'📄'
        },
        {
            classN:'emoji1f4c5',
            wechat:'📅'
        },
        {
            classN:'emoji1f4c1',
            wechat:'📁'
        },
        {
            classN:'emoji1f4c2',
            wechat:'📂'
        },
        {
            classN:'emoji1f4d3',
            wechat:'📓'
        },
        {
            classN:'emoji1f4d6',
            wechat:'📖'
        },
        {
            classN:'emoji1f4d4',
            wechat:'📔'
        },
        {
            classN:'emoji1f4d5',
            wechat:'📕'
        },
        {
            classN:'emoji1f4d7',
            wechat:'📗'
        },
        {
            classN:'emoji1f4d8',
            wechat:'📘'
        },
        {
            classN:'emoji1f4d9',
            wechat:'📙'
        },
        {
            classN:'emoji1f4da',
            wechat:'📚'
        },
        {
            classN:'emoji1f4db',
            wechat:'📛'
        },
        {
            classN:'emoji1f4dc',
            wechat:'📜'
        },
        {
            classN:'emoji1f4cb',
            wechat:'📋'
        },
        {
            classN:'emoji1f4c6',
            wechat:'📆'
        },
        {
            classN:'emoji1f4ca',
            wechat:'📊'
        },
        {
            classN:'emoji1f4c8',
            wechat:'📈'
        },
        {
            classN:'emoji1f4c9',
            wechat:'📉'
        },
        {
            classN:'emoji1f4c7',
            wechat:'📇'
        },
        {
            classN:'emoji1f4cc',
            wechat:'📌'
        },
        {
            classN:'emoji1f4d2',
            wechat:'📒'
        },
        {
            classN:'emoji1f4cf',
            wechat:'📏'
        },
        {
            classN:'emoji1f4d0',
            wechat:'📐'
        },
        {
            classN:'emoji1f4d1',
            wechat:'📑'
        },
        {
            classN:'emoji1f3bd',
            wechat:'🎽'
        },
        {
            classN:'emoji26be',
            wechat:'⚾'
        },
        {
            classN:'emoji26f3',
            wechat:'⛳'
        },
        {
            classN:'emoji1f3be',
            wechat:'🎾'
        },
        {
            classN:'emoji26bd',
            wechat:'⚽'
        },
        {
            classN:'emoji1f3bf',
            wechat:'🎿'
        },
        {
            classN:'emoji1f3c0',
            wechat:'🏀'
        },
        {
            classN:'emoji1f3c1',
            wechat:'🏁'
        },
        {
            classN:'emoji1f3c2',
            wechat:'🏂'
        },
        {
            classN:'emoji1f3c3',
            wechat:'🏃'
        },
        {
            classN:'emoji1f3c4',
            wechat:'🏄'
        },
        {
            classN:'emoji1f3c6',
            wechat:'🏆'
        },
        {
            classN:'emoji1f3c8',
            wechat:'🏈'
        },
        {
            classN:'emoji1f3ca',
            wechat:'🏊'
        },
        {
            classN:'emoji1f683',
            wechat:'🚃'
        },
        {
            classN:'emoji1f687',
            wechat:'🚇'
        },
        {
            classN:'emoji24c2',
            wechat:'Ⓜ'
        },
        {
            classN:'emoji1f684',
            wechat:'🚄'
        },
        {
            classN:'emoji1f685',
            wechat:'🚅'
        },
        {
            classN:'emoji1f697',
            wechat:'🚗'
        },
        {
            classN:'emoji1f699',
            wechat:'🚙'
        },
        {
            classN:'emoji1f68c',
            wechat:'🚌'
        },
        {
            classN:'emoji1f68f',
            wechat:'🚏'
        },
        {
            classN:'emoji1f6a2',
            wechat:'🚢'
        },
        {
            classN:'emoji2708',
            wechat:'✈'
        },
        {
            classN:'emoji26f5',
            wechat:'⛵'
        },
        {
            classN:'emoji1f689',
            wechat:'🚉'
        },
        {
            classN:'emoji1f680',
            wechat:'🚀'
        },
        {
            classN:'emoji1f6a4',
            wechat:'🚤'
        },
        {
            classN:'emoji1f695',
            wechat:'🚕'
        },
        {
            classN:'emoji1f69a',
            wechat:'🚚'
        },
        {
            classN:'emoji1f692',
            wechat:'🚒'
        },
        {
            classN:'emoji1f691',
            wechat:'🚑'
        },
        {
            classN:'emoji1f693',
            wechat:'🚓'
        },
        {
            classN:'emoji26fd',
            wechat:'⛽'
        },
        {
            classN:'emoji1f17f',
            wechat:'🅿'
        },
        {
            classN:'emoji1f6a5',
            wechat:'🚥'
        },
        {
            classN:'emoji1f6a7',
            wechat:'🚧'
        },
        {
            classN:'emoji1f6a8',
            wechat:'🚨'
        },
        {
            classN:'emoji2668',
            wechat:'♨'
        },
        {
            classN:'emoji26fa',
            wechat:'⛺'
        },
        {
            classN:'emoji1f3a0',
            wechat:'🎠'
        },
        {
            classN:'emoji1f3a1',
            wechat:'🎡'
        },
        {
            classN:'emoji1f3a2',
            wechat:'🎢'
        },
        {
            classN:'emoji1f3a3',
            wechat:'🎣'
        },
        {
            classN:'emoji1f3a4',
            wechat:'🎤'
        },
        {
            classN:'emoji1f3a5',
            wechat:'🎥'
        },
        {
            classN:'emoji1f3a6',
            wechat:'🎦'
        },
        {
            classN:'emoji1f3a7',
            wechat:'🎧'
        },
        {
            classN:'emoji1f3a8',
            wechat:'🎨'
        },
        {
            classN:'emoji1f3a9',
            wechat:'🎩'
        },
        {
            classN:'emoji1f3aa',
            wechat:'🎪'
        },
        {
            classN:'emoji1f3ab',
            wechat:'🎫'
        },
        {
            classN:'emoji1f3ac',
            wechat:'🎬'
        },
        {
            classN:'emoji1f3ad',
            wechat:'🎭'
        },
        {
            classN:'emoji1f3ae',
            wechat:'🎮'
        },
        {
            classN:'emoji1f004',
            wechat:'🀄'
        },
        {
            classN:'emoji1f3af',
            wechat:'🎯'
        },
        {
            classN:'emoji1f3b0',
            wechat:'🎰'
        },
        {
            classN:'emoji1f3b1',
            wechat:'🎱'
        },
        {
            classN:'emoji1f3b2',
            wechat:'🎲'
        },
        {
            classN:'emoji1f3b3',
            wechat:'🎳'
        },
        {
            classN:'emoji1f3b4',
            wechat:'🎴'
        },
        {
            classN:'emoji1f0cf',
            wechat:'🃏'
        },
        {
            classN:'emoji1f3b5',
            wechat:'🎵'
        },
        {
            classN:'emoji1f3b6',
            wechat:'🎶'
        },
        {
            classN:'emoji1f3b7',
            wechat:'🎷'
        },
        {
            classN:'emoji1f3b8',
            wechat:'🎸'
        },
        {
            classN:'emoji1f3b9',
            wechat:'🎹'
        },
        {
            classN:'emoji1f3ba',
            wechat:'🎺'
        },
        {
            classN:'emoji1f3bb',
            wechat:'🎻'
        },
        {
            classN:'emoji1f3bc',
            wechat:'🎼'
        },
        {
            classN:'emoji303d',
            wechat:'〽'
        },
        {
            classN:'emoji1f4f7',
            wechat:'📷'
        },
        {
            classN:'emoji1f4f9',
            wechat:'📹'
        },
        {
            classN:'emoji1f4fa',
            wechat:'📺'
        },
        {
            classN:'emoji1f4fb',
            wechat:'📻'
        },
        {
            classN:'emoji1f4fc',
            wechat:'📼'
        },
        {
            classN:'emoji1f48b',
            wechat:'💋'
        },
        {
            classN:'emoji1f48c',
            wechat:'💌'
        },
        {
            classN:'emoji1f48d',
            wechat:'💍'
        },
        {
            classN:'emoji1f48e',
            wechat:'💎'
        },
        {
            classN:'emoji1f48f',
            wechat:'💏'
        },
        {
            classN:'emoji1f490',
            wechat:'💐'
        },
        {
            classN:'emoji1f491',
            wechat:'💑'
        },
        {
            classN:'emoji1f492',
            wechat:'💒'
        },
        {
            classN:'emoji1f51e',
            wechat:'🔞'
        },
        {
            classN:'emojia9',
            wechat:'©'
        },
        {
            classN:'emojiae',
            wechat:'®'
        },
        {
            classN:'emoji2122',
            wechat:'™'
        },
        {
            classN:'emoji2139',
            wechat:'ℹ'
        },
        {
            classN:'emoji1f51f',
            wechat:'🔟'
        },
        {
            classN:'emoji1f4f6',
            wechat:'📶'
        },
        {
            classN:'emoji1f4f3',
            wechat:'📳'
        },
        {
            classN:'emoji1f4f4',
            wechat:'📴'
        },
        {
            classN:'emoji1f354',
            wechat:'🍔'
        },
        {
            classN:'emoji1f359',
            wechat:'🍙'
        },
        {
            classN:'emoji1f370',
            wechat:'🍰'
        },
        {
            classN:'emoji1f35c',
            wechat:'🍜'
        },
        {
            classN:'emoji1f35e',
            wechat:'🍞'
        },
        {
            classN:'emoji1f373',
            wechat:'🍳'
        },
        {
            classN:'emoji1f366',
            wechat:'🍦'
        },
        {
            classN:'emoji1f35f',
            wechat:'🍟'
        },
        {
            classN:'emoji1f361',
            wechat:'🍡'
        },
        {
            classN:'emoji1f358',
            wechat:'🍘'
        },
        {
            classN:'emoji1f35a',
            wechat:'🍚'
        },
        {
            classN:'emoji1f35d',
            wechat:'🍝'
        },
        {
            classN:'emoji1f35b',
            wechat:'🍛'
        },
        {
            classN:'emoji1f362',
            wechat:'🍢'
        },
        {
            classN:'emoji1f363',
            wechat:'🍣'
        },
        {
            classN:'emoji1f371',
            wechat:'🍱'
        },
        {
            classN:'emoji1f372',
            wechat:'🍲'
        },
        {
            classN:'emoji1f367',
            wechat:'🍧'
        },
        {
            classN:'emoji1f356',
            wechat:'🍖'
        },
        {
            classN:'emoji1f365',
            wechat:'🍥'
        },
        {
            classN:'emoji1f360',
            wechat:'🍠'
        },
        {
            classN:'emoji1f355',
            wechat:'🍕'
        },
        {
            classN:'emoji1f357',
            wechat:'🍗'
        },
        {
            classN:'emoji1f368',
            wechat:'🍨'
        },
        {
            classN:'emoji1f369',
            wechat:'🍩'
        },
        {
            classN:'emoji1f36a',
            wechat:'🍪'
        },
        {
            classN:'emoji1f36b',
            wechat:'🍫'
        },
        {
            classN:'emoji1f36c',
            wechat:'🍬'
        },
        {
            classN:'emoji1f36d',
            wechat:'🍭'
        },
        {
            classN:'emoji1f36e',
            wechat:'🍮'
        },
        {
            classN:'emoji1f36f',
            wechat:'🍯'
        },
        {
            classN:'emoji1f364',
            wechat:'🍤'
        },
        {
            classN:'emoji1f374',
            wechat:'🍴'
        },
        {
            classN:'emoji2615',
            wechat:'☕'
        },
        {
            classN:'emoji1f378',
            wechat:'🍸'
        },
        {
            classN:'emoji1f37a',
            wechat:'🍺'
        },
        {
            classN:'emoji1f375',
            wechat:'🍵'
        },
        {
            classN:'emoji1f376',
            wechat:'🍶'
        },
        {
            classN:'emoji1f377',
            wechat:'🍷'
        },
        {
            classN:'emoji1f37b',
            wechat:'🍻'
        },
        {
            classN:'emoji1f379',
            wechat:'🍹'
        },
        {
            classN:'emoji2197',
            wechat:'↗'
        },
        {
            classN:'emoji2198',
            wechat:'↘'
        },
        {
            classN:'emoji2196',
            wechat:'↖'
        },
        {
            classN:'emoji2199',
            wechat:'↙'
        },
        {
            classN:'emoji2934',
            wechat:'⤴'
        },
        {
            classN:'emoji2935',
            wechat:'⤵'
        },
        {
            classN:'emoji2194',
            wechat:'↔'
        },
        {
            classN:'emoji2195',
            wechat:'↕'
        },
        {
            classN:'emoji2b06',
            wechat:'⬆'
        },
        {
            classN:'emoji2b07',
            wechat:'⬇'
        },
        {
            classN:'emoji27a1',
            wechat:'➡'
        },
        {
            classN:'emoji2b05',
            wechat:'⬅'
        },
        {
            classN:'emoji25b6',
            wechat:'▶'
        },
        {
            classN:'emoji25c0',
            wechat:'◀'
        },
        {
            classN:'emoji23000000000',
            wechat:'⏩'
        },
        {
            classN:'emoji23ea',
            wechat:'⏪'
        },
        {
            classN:'emoji23eb',
            wechat:'⏫'
        },
        {
            classN:'emoji23ec',
            wechat:'⏬'
        },
        {
            classN:'emoji1f53a',
            wechat:'🔺'
        },
        {
            classN:'emoji1f53b',
            wechat:'🔻'
        },
        {
            classN:'emoji1f53c',
            wechat:'🔼'
        },
        {
            classN:'emoji1f53d',
            wechat:'🔽'
        },
        {
            classN:'emoji2b55',
            wechat:'⭕'
        },
        {
            classN:'emoji274c',
            wechat:'❌'
        },
        {
            classN:'emoji274e',
            wechat:'❎'
        },
        {
            classN:'emoji2757',
            wechat:'❗'
        },
        {
            classN:'emoji2049',
            wechat:'⁉'
        },
        {
            classN:'emoji203c',
            wechat:'‼'
        },
        {
            classN:'emoji2753',
            wechat:'❓'
        },
        {
            classN:'emoji2754',
            wechat:'❔'
        },
        {
            classN:'emoji2755',
            wechat:'❕'
        },
        {
            classN:'emoji3030',
            wechat:'〰'
        },
        {
            classN:'emoji27b0',
            wechat:'➰'
        },

        {
            classN:'emoji2764',
            wechat:'❤'
        },
        {
            classN:'emoji1f493',
            wechat:'💓'
        },
        {
            classN:'emoji1f494',
            wechat:'💔'
        },
        {
            classN:'emoji1f495',
            wechat:'💕'
        },
        {
            classN:'emoji1f496',
            wechat:'💖'
        },
        {
            classN:'emoji1f497',
            wechat:'💗'
        },
        {
            classN:'emoji1f498',
            wechat:'💘'
        },
        {
            classN:'emoji1f499',
            wechat:'💙'
        },
        {
            classN:'emoji1f49a',
            wechat:'💚'
        },
        {
            classN:'emoji1f49b',
            wechat:'💛'
        },
        {
            classN:'emoji1f49c',
            wechat:'💜'
        },
        {
            classN:'emoji1f49d',
            wechat:'💝'
        },
        {
            classN:'emoji1f49e',
            wechat:'💞'
        },
        {
            classN:'emoji1f49f',
            wechat:'💟'
        },
        {
            classN:'emoji2665',
            wechat:'♥'
        },
        {
            classN:'emoji2660',
            wechat:'♠'
        },
        {
            classN:'emoji2666',
            wechat:'♦'
        },
        {
            classN:'emoji2663',
            wechat:'♣'
        },
        {
            classN:'emoji1f6ac',
            wechat:'🚬'
        },
        {
            classN:'emoji1f6ad',
            wechat:'🚭'
        },
        {
            classN:'emoji267f',
            wechat:'♿'
        },
        {
            classN:'emoji1f6a9',
            wechat:'🚩'
        },
        {
            classN:'emoji26a0',
            wechat:'⚠'
        },
        {
            classN:'emoji26d4',
            wechat:'⛔'
        },
        {
            classN:'emoji267b',
            wechat:'♻'
        },
        {
            classN:'emoji1f6b2',
            wechat:'🚲'
        },
        {
            classN:'emoji1f6b6',
            wechat:'🚶'
        },
        {
            classN:'emoji1f6b9',
            wechat:'🚹'
        },
        {
            classN:'emoji1f6ba',
            wechat:'🚺'
        },
        {
            classN:'emoji1f6c0',
            wechat:'🛀'
        },
        {
            classN:'emoji1f6bb',
            wechat:'🚻'
        },
        {
            classN:'emoji1f6bd',
            wechat:'🚽'
        },
        {
            classN:'emoji1f6be',
            wechat:'🚾'
        },
        {
            classN:'emoji1f6bc',
            wechat:'🚼'
        },
        {
            classN:'emoji1f6aa',
            wechat:'🚪'
        },
        {
            classN:'emoji1f6ab',
            wechat:'🚫'
        },
        {
            classN:'emoji2714',
            wechat:'✔'
        },
        {
            classN:'emoji1f191',
            wechat:'🆑'
        },
        {
            classN:'emoji1f192',
            wechat:'🆒'
        },
        {
            classN:'emoji1f193',
            wechat:'🆓'
        },
        {
            classN:'emoji1f194',
            wechat:'🆔'
        },
        {
            classN:'emoji1f195',
            wechat:'🆕'
        },
        {
            classN:'emoji1f196',
            wechat:'🆖'
        },
        {
            classN:'emoji1f197',
            wechat:'🆗'
        },
        {
            classN:'emoji1f198',
            wechat:'🆘'
        },
        {
            classN:'emoji1f199',
            wechat:'🆙'
        },
        {
            classN:'emoji1f19a',
            wechat:'🆚'
        },
        {
            classN:'emoji1f201',
            wechat:'🈁'
        },
        {
            classN:'emoji1f202',
            wechat:'🈂'
        },
        {
            classN:'emoji1f232',
            wechat:'🈲'
        },
        {
            classN:'emoji1f233',
            wechat:'🈳'
        },
        {
            classN:'emoji1f234',
            wechat:'🈴'
        },
        {
            classN:'emoji1f235',
            wechat:'🈵'
        },
        {
            classN:'emoji1f236',
            wechat:'🈶'
        },
        {
            classN:'emoji1f21a',
            wechat:'🈚'
        },
        {
            classN:'emoji1f237',
            wechat:'🈷'
        },
        {
            classN:'emoji1f238',
            wechat:'🈸'
        },
        {
            classN:'emoji1f239',
            wechat:'🈹'
        },
        {
            classN:'emoji1f22f',
            wechat:'🈯'
        },
        {
            classN:'emoji1f23a',
            wechat:'🈺'
        },
        {
            classN:'emoji3299',
            wechat:'㊙'
        },
        {
            classN:'emoji3297',
            wechat:'㊗'
        },
        {
            classN:'emoji1f250',
            wechat:'🉐'
        },
        {
            classN:'emoji1f251',
            wechat:'🉑'
        },
        {
            classN:'emoji2795',
            wechat:'➕'
        },
        {
            classN:'emoji2796',
            wechat:'➖'
        },
        {
            classN:'emoji2716',
            wechat:'✖'
        },
        {
            classN:'emoji2797',
            wechat:'➗'
        },
        {
            classN:'emoji1f4a0',
            wechat:'💠'
        },
        {
            classN:'emoji1f4a1',
            wechat:'💡'
        },
        {
            classN:'emoji1f4a2',
            wechat:'💢'
        },
        {
            classN:'emoji1f4a3',
            wechat:'💣'
        },
        {
            classN:'emoji1f4a4',
            wechat:'💤'
        },
        {
            classN:'emoji1f4a5',
            wechat:'💥'
        },
        {
            classN:'emoji1f4a6',
            wechat:'💦'
        },
        {
            classN:'emoji1f4a7',
            wechat:'💧'
        },
        {
            classN:'emoji1f4a8',
            wechat:'💨'
        },
        {
            classN:'emoji1f4a9',
            wechat:'💩'
        },
        {
            classN:'emoji1f4aa',
            wechat:'💪'
        },
        {
            classN:'emoji1f4ab',
            wechat:'💫'
        },
        {
            classN:'emoji1f4ac',
            wechat:'💬'
        },
        {
            classN:'emoji2728',
            wechat:'✨'
        },
        {
            classN:'emoji2734',
            wechat:'✴'
        },
        {
            classN:'emoji2733',
            wechat:'✳'
        },
        {
            classN:'emoji26aa',
            wechat:'⚪'
        },
        {
            classN:'emoji26ab',
            wechat:'⚫'
        },
        {
            classN:'emoji1f534',
            wechat:'🔴'
        },
        {
            classN:'emoji1f535',
            wechat:'🔵'
        },
        {
            classN:'emoji1f532',
            wechat:'🔲'
        },
        {
            classN:'emoji1f533',
            wechat:'🔳'
        },
        {
            classN:'emoji2b50',
            wechat:'⭐'
        },
        {
            classN:'emoji2b1c',
            wechat:'⬜'
        },
        {
            classN:'emoji2b1b',
            wechat:'⬛'
        },
        {
            classN:'emoji25ab',
            wechat:'▫'
        },
        {
            classN:'emoji25aa',
            wechat:'▪'
        },
        {
            classN:'emoji25fd',
            wechat:'◽'
        },
        {
            classN:'emoji25fe',
            wechat:'◾'
        },
        {
            classN:'emoji25fb',
            wechat:'◻'
        },
        {
            classN:'emoji25fc',
            wechat:'◼'
        },
        {
            classN:'emoji1f536',
            wechat:'🔶'
        },
        {
            classN:'emoji1f537',
            wechat:'🔷'
        },
        {
            classN:'emoji1f538',
            wechat:'🔸'
        },
        {
            classN:'emoji1f539',
            wechat:'🔹'
        },
        {
            classN:'emoji2747',
            wechat:'❇'
        },
        {
            classN:'emoji1f4ae',
            wechat:'💮'
        },
        {
            classN:'emoji1f4af',
            wechat:'💯'
        },
        {
            classN:'emoji21a9',
            wechat:'↩'
        },
        {
            classN:'emoji21aa',
            wechat:'↪'
        },
        {
            classN:'emoji1f503',
            wechat:'🔃'
        },
        {
            classN:'emoji1f50a',
            wechat:'🔊'
        },
        {
            classN:'emoji1f50b',
            wechat:'🔋'
        },
        {
            classN:'emoji1f50c',
            wechat:'🔌'
        },
        {
            classN:'emoji1f50d',
            wechat:'🔍'
        },
        {
            classN:'emoji1f50e',
            wechat:'🔎'
        },
        {
            classN:'emoji1f512',
            wechat:'🔒'
        },
        {
            classN:'emoji1f513',
            wechat:'🔓'
        },
        {
            classN:'emoji1f50f',
            wechat:'🔏'
        },
        {
            classN:'emoji1f510',
            wechat:'🔐'
        },
        {
            classN:'emoji1f511',
            wechat:'🔑'
        },
        {
            classN:'emoji1f514',
            wechat:'🔔'
        },
        {
            classN:'emoji2611',
            wechat:'☑'
        },
        {
            classN:'emoji1f518',
            wechat:'🔘'
        },
        {
            classN:'emoji1f516',
            wechat:'🔖'
        },
        {
            classN:'emoji1f517',
            wechat:'🔗'
        },
        {
            classN:'emoji1f519',
            wechat:'🔙'
        },
        {
            classN:'emoji1f51a',
            wechat:'🔚'
        },
        {
            classN:'emoji1f51b',
            wechat:'🔛'
        },
        {
            classN:'emoji1f51c',
            wechat:'🔜'
        },
        {
            classN:'emoji1f51d',
            wechat:'🔝'
        },
        {
            classN:'emoji2705',
            wechat:'✅'
        },
        {
            classN:'emoji270a',
            wechat:'✊'
        },
        {
            classN:'emoji270b',
            wechat:'✋'
        },
        {
            classN:'emoji270c',
            wechat:'✌'
        },
        {
            classN:'emoji1f44a',
            wechat:'👊'
        },
        {
            classN:'emoji1f44d',
            wechat:'👍'
        },
        {
            classN:'emoji261d',
            wechat:'☝'
        },
        {
            classN:'emoji1f446',
            wechat:'👆'
        },
        {
            classN:'emoji1f447',
            wechat:'👇'
        },
        {
            classN:'emoji1f448',
            wechat:'👈'
        },
        {
            classN:'emoji1f449',
            wechat:'👉'
        },
        {
            classN:'emoji1f44b',
            wechat:'👋'
        },
        {
            classN:'emoji1f44f',
            wechat:'👏'
        },
        {
            classN:'emoji1f44c',
            wechat:'👌'
        },
        {
            classN:'emoji1f44e',
            wechat:'👎'
        },
        {
            classN:'emoji1f450',
            wechat:'👐'
        },

    ];//表情

    return  emojiData;
}
